name: Test Release

on: workflow_dispatch

jobs:
  start:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Versions
        run: |
          node --version
          npm --version
          tsc --version

      - run: |
          cd master
          npm i typescript
          npm run build

      - uses: actions/checkout@v3
        with:
          ref: release
          path: release

      - name: Push Release
        # if: github.ref == 'refs/heads/main'
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          cd release
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@github.com"
          git rm -rf .
          mv -rv ../master/build/dist/*  .
          git add -A
          if [[ -z $(git status -s) ]]
          then
            echo "No changes"
          else
            git commit -m "${GITHUB_REF##*/}: $COMMIT_MESSAGE"
            git push
          fi
